language: node_js
node_js:
  - '8.12.0'

before_install:
  - sudo apt-get install -y w3m
  - w3m -dump -cols 2000 https://tango-argentin.fr/paris |grep '2018\|2019\|Entrée' |sed 's/Transparent\|En savoir plus//g' |awk '{$1=$1};1' |head -n50
addons:
  apt:
    update: true
